language: node_js

os: linux
dist: xenial

node_js:
  - 14
  - 12
  - 10

before_install:
  - npm config set depth 0
before_script:
  - 'if [ "${ESLINT-}" == "7" ]; then npm install --no-save "eslint@${ESLINT}" ; fi'
  - 'if [ "${ESLINT-}" == "6" ]; then npm install --no-save "eslint@${ESLINT}" ; fi'
script:
  - npm run test
  - 'if [ -n "${LINTBUILD-}" ]; then npm run lint && npm run build; fi'
env:
  jobs:
    - ESLINT=7
    - ESLINT=6
jobs:
  # https://docs.travis-ci.com/user/customizing-the-build/#explicitly-including-jobs
  include:
    # https://docs.travis-ci.com/user/build-stages
    - stage: lint
      node_js: 'lts/*'
      env: LINTBUILD=true
    # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/travis.md
    - stage: release
      node_js: lts/*
      # script: skip
      deploy:
        provider: script
        # skip_cleanup: true (deprecated in favor of `cleanup` which defaults to true)
        script:
          - npx semantic-release

# Matrix built by `node_js`, and `env.jobs`, running `script` for each,
#  and running `jobs.include` when criteria (`node_js`) are matched
# To exclude jobs in the default resulting matrix by criteria
#  exclude:
#    - node_js: 6
#      env: ESLINT=6
